name: mlflow_review_demos
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11.4
  - pip
  - pip:
      - mlflow==2.3
      - scikit-learn==0.23.2
      - cloudpickle==1.6.0
      - Flask==2.2.2
      - Jinja2==3.1.2
      - alembic==1.12.0
      - click==8.0.4
      - cloudpickle==2.2.1
      - databricks-cli==0.18.0
      - docker==6.1.3
      - entrypoints==0.4
      - gitpython==3.1.40
      - importlib-metadata==6.0.0
      - markdown==3.4.1
      - matplotlib==3.7.1
      - numpy==1.24.3
      - packaging==23.0
      - pandas==1.5.3
      - protobuf==3.20.3
      - pyarrow==11.0.0
      - pytz==2022.7
      - pyyaml==6.0
      - querystring-parser==1.2.4
      - requests==2.31.0
      - scikit-learn==1.3.0
      - scipy==1.10.1
      - sqlalchemy==1.4.39
      - sqlparse==0.4.4
      - waitress==2.1.2
      - plotnine==0.12.4
      - seaborn==0.12.2
